### ISSUE TITLE
403 error response from https://s3-us-west-2.amazonaws.com/nyzo/000001.nyzotransaction

### ISSUE THREAD

**Issue by EarthlingDavey** [n-y-z-o/nyzoVerifier#11] opened 2019-09-30 16:20 UTC
Hi, I'm getting this error in the logs. Is this an issue or ok?

    java.io.IOException: Server returned HTTP response code: 403 for URL: https://s3-us-west-2.amazonaws.com/nyzo/000001.nyzotransaction
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
    at java.net.URL.openStream(URL.java:1057)
    at co.nyzo.verifier.SeedTransactionManager.fetchFile(SeedTransactionManager.java:133)
    at co.nyzo.verifier.SeedTransactionManager$1.run(SeedTransactionManager.java:77)
    at java.lang.Thread.run(Thread.java:748)

The standard logs look like this...

    requesting block with votes for height 4723359, interval=6858
    trying to fetch BlockWithVotesRequest37 from Voyager
    freezing block [Block:v=1,height=4723359,hash=d9d7...58e3,id=80f2...0e18] with standard mechanism
    $$$$$ removing vote map of size 1409
    cleaning up because block 4723359 was frozen
    casting late vote for height 4723359
    ^^^^^^^^^^^^^^^^^^^^^ casting vote for height 4723359
    top verifier is null
    requesting block with votes for height 4723360, interval=7175
    trying to fetch BlockWithVotesRequest37 from koottum
    freezing block [Block:v=1,height=4723360,hash=de3a...1681,id=3865...5936] with standard mechanism
    $$$$$ removing vote map of size 1409
    cleaning up because block 4723360 was frozen
    casting late vote for height 4723360
    ^^^^^^^^^^^^^^^^^^^^^ casting vote for height 4723360
    top verifier is null
    requesting block with votes for height 4723361, interval=7143
    trying to fetch BlockWithVotesRequest37 from NDream1623
    freezing block [Block:v=1,height=4723361,hash=a012...38ca,id=16bc...12f0] with standard mechanism
    $$$$$ removing vote map of size 1405
    cleaning up because block 4723361 was frozen
    casting late vote for height 4723361
    ^^^^^^^^^^^^^^^^^^^^^ casting vote for height 4723361
    top verifier is null

**Comment by s20coeur** [comment] 2020-05-04 16:14
Hello,

Same issue here, no update on this problem ?

Thx in Advance

**Comment by n-y-z-o** [comment] 2020-05-15 19:10
These files were deliberately removed from access because they were causing significant bandwidth charges from being repeatedly downloaded.

**Comment by huglester** [comment] 2020-05-24 19:29
@n-y-z-o well starting with 586, 587 server, spinning new verifier is a problem.
so to reproduce, imagine you just installed new verifier..
git pull; gradlew build; etc.

and logs show this:
```
unable to fetch Genesis block; retrying
genesis block is null
unable to fetch Genesis block; retryin
```
It just wont start.
Solling back to 580 fixes the problem for example.

**Comment by n-y-z-o** [comment] 2020-05-25 15:26
Thank you for pointing this out. We forgot to transfer the Genesis file to the new location referenced in 586. It has been transferred and is now accessible.

https://seed.nyzo.co/seedTransactions/genesis

The old location of the Genesis block has now been deactivated. Anyone wishing to use the files we host must upgrade to 586 or later, as the endpoints in 585 and sooner will be fully deactivated soon.

**Comment by n-y-z-o** [comment] 2022-03-06 22:12
Closing this issue because it was no longer relevant after version 585.

**Closed by n-y-z-o** 2022-03-06 22:12 UTC
